In [1]:
#引入使用的模块
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.io import loadmat

In [2]:
#处理并查看数据
data=loadmat('F:\\Machinelearning\data\ex3data1')
print(data)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011', '__version__': '1.0', '__globals__': [], 'X': array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]]), 'y': array([[10],
       [10],
       [10],
       ...,
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)}


In [3]:
X=data['X']
y=data['y']
print(X.shape,y.shape)

(5000, 400) (5000, 1)


In [4]:
#定义logistic函数
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [5]:
#给X加常数列，处理偏转项；定义theta
m,d=X.shape
X=np.insert(X,0,1,axis=1)
theta=np.zeros(d+1)
y=y.reshape((m,))
print(X.shape,y.shape,theta.shape)
print(X)

(5000, 401) (5000,) (401,)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [6]:
def regularized_Cost(X,y,theta,regular_param):
    m=X.shape[0]
    cost=-np.mean(y*np.log(sigmoid(X@theta))+(1-y)*np.log(1-sigmoid(X@theta)))
    reg_term=(theta[1:].T@theta[1:])/(2*m)
    return cost+reg_term
print(regularized_Cost(X,y,theta,1))

160.39425758157134


In [7]:
def reg_Gradient(X,y,theta,regular_param):
    m=X.shape[0]
    delta_Vector=sigmoid(X@theta)-y
    gradient=(X.T@delta_Vector)/m
    theta1=theta[1:]
    theta1=np.insert(theta1,0,0)
    reg_term=theta1*regular_param/m
    return gradient+reg_term,reg_term.shape,gradient.shape
print(reg_Gradient(X,y,theta,1))

(array([-5.00000000e+00,  0.00000000e+00,  0.00000000e+00, -7.74530186e-08,
        3.19876600e-06,  1.89536237e-05, -7.06376094e-04, -8.97395355e-04,
       -3.72741263e-04, -1.10787541e-04, -1.37049401e-04, -4.11905416e-05,
        3.09307938e-05,  7.56273049e-05,  1.66101324e-04,  1.88959823e-04,
        1.11618541e-04,  3.44740605e-05,  2.31849497e-07, -3.65944989e-07,
        0.00000000e+00, -2.71480120e-07,  2.68348312e-06,  1.35802658e-06,
        5.10971729e-05,  9.29459372e-05, -1.13518367e-03, -4.04630781e-03,
       -5.65616107e-03, -4.38249876e-03, -1.22936584e-03,  1.06402725e-03,
        1.67724463e-03,  1.83122226e-03,  1.41359436e-03,  1.00669534e-03,
        6.22600175e-04,  2.88468971e-04,  1.69300222e-04,  4.53328568e-05,
        1.64277642e-05,  2.32894093e-06, -2.61429416e-05,  6.07579192e-05,
       -2.68789968e-04, -2.19152610e-03, -1.11673884e-02, -2.41869621e-02,
       -3.12963830e-02, -2.35164217e-02, -1.04915336e-02, -4.58342103e-03,
       -2.20552420e-03, 

In [8]:
from scipy.optimize import minimize
def one_vs_all(X,y,classNum,Reg_Param):
    all_theta=np.zeros((classNum,d+1))
    for i in range(classNum):
        y1=[1 if i+1==label else 0 for label in y]
        fmin=minimize(fun=regularized_Cost,x0=theta,args=(X,y,Reg_Param),method='TNC',jac=reg_Gradient)
        all_theta[i,:]=fmin.x
    return all_theta
print(one_vs_all(X,y,10,1))

ValueError: shapes (401,) and (5000,) not aligned: 401 (dim 0) != 5000 (dim 0)